* helheim-consult
[[https://github.com/minad/consult][
Consult]] package provides a set of search and preview commands.

** Enable
#+begin_src emacs-lisp
(require 'helheim-consult)
#+end_src

** Usage

A few keybinding highlights from my day-to-day usage, to provide inspiration and
a smooth start.

- =C-/= (~consult-line~) ::
  A universal line-by-line search within the current buffer. Mnemonic: =/= is the
  search key in Hel Normal state (following Vim). Binding it to =C-/= makes it
  accessable both in editing buffers (in Hel Normal state) and in special
  buffers (in Hel Motion state).

- =Space /= (~consult-ripgrep~) ::
  Search in current project with ripgrep and show results in minibuffer.
  Use =C-c C-c= to export them to ~grep-mode~ buffer.

- =i= ::
  In practically all buffers with search results: ~grep-mode~, ~deadgrep-mode~,
  ~occur-mode~, you can switch to Insert state for editing original files directly
  from a search results buffer. To switch back to Motion state use =ZZ= or =zx= or
  =C-c C-c=.

  The only place where it doesn't work is Xref buffer (~xref--xref-buffer-mode~).

- =Space s r= :: Search and replace string literally.
- =Space s R= :: Search and replace Emacs regexp.


