* helheim-searhc
** Enable
#+begin_src emacs-lisp
(require 'helheim-search)
#+end_src* Enable

** Consult
[[https://github.com/minad/consult][
Consult]] package provides a set of search and preview commands.

A few keybinding highlights from my day-to-day usage, to provide inspiration
and a smooth start.

- =g RET= (~consult-goto-line~) :: Read line number and jump to it.

- =g m= (~consult-mark~) :: Buffer-local jump list.
- =g M= (~consult-global-mark~) :: Global jump list.

- =C-/= (~consult-line~) ::
  A universal line-by-line search within the current buffer. Mnemonic: =/= is
  the search key in Hel Normal state (following Vim). Binding it to =C-/= makes
  it accessable both in editing buffers (in Hel Normal state) and in special
  buffers (in Hel Emacs state).

- =Space /= (~consult-ripgrep~) ::
  Search in current project with ripgrep and show results in minibuffer.
  Use =C-c C-c= (~embark-export~) to export them to ~grep-mode~ buffer.

- =Space s r= (~query-replace~) ::
  Search and replace string literally.

- =Space s R= (~query-replace-regexp~) ::
  Search and replace Emacs regexp.

- =i= ::
  In practically all buffers with search results: ~grep-mode~, ~deadgrep-mode~,
  ~occur-mode~, you can switch to Insert state for editing original files directly
  from a search results buffer. To switch back to Emacs state use =ZZ= or =zx= or
  =C-c C-c=.

  The only place where it doesn't work is Xref buffer (~xref--xref-buffer-mode~).

** Deadgrep

- =SPC s s= :: Start a ripgrep search.

*** Automatically show preveiw in other window

If you want a preview in other window follows your moves in deadgrep buffer:
#+begin_src emacs-lisp
(add-hook 'deadgrep-mode-hook #'next-error-follow-minor-mode)
#+end_src


